name: Post welcome gosbito
on:
  pull_request:
    type: [opened]
permissions:
  pull_requests: write
jobs:
  build:
    name: Post welcome gosbito
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "\n\n\nwelcome gosbito\n\n\n"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
